# Two services: backend API on 5000, frontend (nginx) on 80
services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env        
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://116.62.135.53:5001/api
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend